# ---------- PersistentVolumeClaim ----------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi            # tamaño del disco; ajústalo si necesitas más
  # Sin storageClassName → Minikube usará la clase por defecto (“standard”)

---
# ---------- Deployment ----------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      # Garantiza que el volumen quede accesible al UID/GID 999 (usuario postgres)
      securityContext:
        fsGroup: 999          # grupo del proceso postgres dentro del contenedor
      containers:
      - name: postgres
        image: postgres:15-alpine          # versión ligera y actual
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: database_admin
          - name: POSTGRES_PASSWORD
            value: "1234"
          - name: POSTGRES_DB
            value: movies_recommender
        volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data   # directorio de datos
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc

---
# ---------- Service ----------
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
