apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prediction-api
  template:
    metadata:
      labels:
        app: prediction-api
    spec:
      containers:
      - name: prediction-api
        image: prediction-api:latest
        imagePullPolicy: Never
        env:
        - name: SERVER
          value: "postgres-service"
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /predict?user_id=1
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: prediction-service
spec:
  selector:
    app: prediction-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000